branch-defaults:
  default:
    environment: MaidenThoughts-dev
    group_suffix: null
global:
  application_name: MaidenThoughts
  default_ec2_keyname: MyKeyPair
  default_platform: Python 2.7
  default_region: us-west-2
  profile: eb-cli
  sc: null
